BEGIN;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE app_user (
id INT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email CITEXT UNIQUE NOT NULL,
password_hash VARCHAR(200) NOT NULL
);
COMMIT;