BEGIN;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE app_user (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email CITEXT UNIQUE NOT NULL CHECK (email ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$'),
password_hash VARCHAR(200) NOT NULL
);
COMMIT;